
package stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExpectedApprovalSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExpectedApprovalSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "stub.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "stub.HelloWorldResponse")
    public String helloWorld();

    /**
     * 
     * @param waitWork
     * @return
     *     returns stub.NotifyTodoAppResult
     */
    @WebMethod(operationName = "InsertWork", action = "http://tempuri.org/InsertWork")
    @WebResult(name = "InsertWorkResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InsertWork", targetNamespace = "http://tempuri.org/", className = "stub.InsertWork")
    @ResponseWrapper(localName = "InsertWorkResponse", targetNamespace = "http://tempuri.org/", className = "stub.InsertWorkResponse")
    public NotifyTodoAppResult insertWork(
        @WebParam(name = "waitWork", targetNamespace = "http://tempuri.org/")
        WaitWork waitWork);

    /**
     * 
     * @param strWaitID
     * @return
     *     returns stub.NotifyTodoAppResult
     */
    @WebMethod(operationName = "DeleteWork", action = "http://tempuri.org/DeleteWork")
    @WebResult(name = "DeleteWorkResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DeleteWork", targetNamespace = "http://tempuri.org/", className = "stub.DeleteWork")
    @ResponseWrapper(localName = "DeleteWorkResponse", targetNamespace = "http://tempuri.org/", className = "stub.DeleteWorkResponse")
    public NotifyTodoAppResult deleteWork(
        @WebParam(name = "strWaitID", targetNamespace = "http://tempuri.org/")
        String strWaitID);

}
