
package stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExpectedApproval", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/D:/tempvi/WaitWorkCenter.asmx.wsdl")
public class ExpectedApproval
    extends Service
{

    private final static URL EXPECTEDAPPROVAL_WSDL_LOCATION;
    private final static WebServiceException EXPECTEDAPPROVAL_EXCEPTION;
    private final static QName EXPECTEDAPPROVAL_QNAME = new QName("http://tempuri.org/", "ExpectedApproval");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/tempvi/WaitWorkCenter.asmx.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXPECTEDAPPROVAL_WSDL_LOCATION = url;
        EXPECTEDAPPROVAL_EXCEPTION = e;
    }

    public ExpectedApproval() {
        super(__getWsdlLocation(), EXPECTEDAPPROVAL_QNAME);
    }

    public ExpectedApproval(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXPECTEDAPPROVAL_QNAME, features);
    }

    public ExpectedApproval(URL wsdlLocation) {
        super(wsdlLocation, EXPECTEDAPPROVAL_QNAME);
    }

    public ExpectedApproval(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXPECTEDAPPROVAL_QNAME, features);
    }

    public ExpectedApproval(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExpectedApproval(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExpectedApprovalSoap
     */
    @WebEndpoint(name = "ExpectedApprovalSoap")
    public ExpectedApprovalSoap getExpectedApprovalSoap() {
        return super.getPort(new QName("http://tempuri.org/", "ExpectedApprovalSoap"), ExpectedApprovalSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExpectedApprovalSoap
     */
    @WebEndpoint(name = "ExpectedApprovalSoap")
    public ExpectedApprovalSoap getExpectedApprovalSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ExpectedApprovalSoap"), ExpectedApprovalSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXPECTEDAPPROVAL_EXCEPTION!= null) {
            throw EXPECTEDAPPROVAL_EXCEPTION;
        }
        return EXPECTEDAPPROVAL_WSDL_LOCATION;
    }

}
